WITH ALL_SUBSCRIPTIONS AS (
    SELECT
        SUBSCRIPTIONID,
        EXPIRATIONDATE
    FROM
        SUBSCRIPTIONSPRODUCT1
    WHERE
        ACTIVE = 1
    
    UNION ALL

    SELECT
        SUBSCRIPTIONID,
        EXPIRATIONDATE
    FROM
        SUBSCRIPTIONSPRODUCT2
    WHERE
        ACTIVE = 1
)
SELECT
    DATE_TRUNC('year', EXPIRATIONDATE) AS EXP_YEAR,
    COUNT(*) AS SUBSCRIPTIONS
FROM
    ALL_SUBSCRIPTIONS
GROUP BY
    DATE_TRUNC('year', EXPIRATIONDATE)