SELECT
    USERID,
    SUM(CASE WHEN el.EVENTID = 1 THEN 1 ELSE 0 END) AS ViewedHelpCenterPage,
    SUM(CASE WHEN el.EVENTID = 2 THEN 1 ELSE 0 END) AS ClickedFAQs,
    SUM(CASE WHEN el.EVENTID = 3 THEN 1 ELSE 0 END) AS ClickedContactSupport,
    SUM(CASE WHEN el.EVENTID = 4 THEN 1 ELSE 0 END) AS SubmittedTicket
FROM
    FRONTENDEVENTLOG AS el
JOIN
    FRONTENDEVENTDEFINITIONS AS def
    ON el.EVENTID = def.EVENTID
WHERE
    EVENTTYPE = 'Customer Support'
GROUP BY
    USERID;