WITH SALES_RANKS AS (
    SELECT
        SALESEMPLOYEEID,
        SALESAMOUNT,
        SALESDATE,
        ROW_NUMBER() OVER(PARTITION BY SALESEMPLOYEEID ORDER BY SALESDATE DESC) AS MOST_RECENT_SALE
    FROM
        SALES
)

SELECT
    *
FROM
    SALES_RANKS
WHERE
    MOST_RECENT_SALE = 1;