SELECT
    SALESEMPLOYEEID,
    SALEDATE,
    SALEAMOUNT,
    SUM(SALEAMOUNT)
        OVER(PARTITION BY SALESEMPLOYEEID
            ORDER BY SALEDATE) AS RUNNING_TOTAL,
    CAST(SUM(SALEAMOUNT)
        OVER(PARTITION BY SALESEMPLOYEEID
            ORDER BY SALEDATE) AS FLOAT)
        /
        QUOTA AS PERCENT_QUOTA
FROM
    SALES AS S
JOIN
    EMPLOYEES AS E
ON S.SALESEMPLOYEEID = E.EMPLOYEEID;